import { useState } from "react";
import { ArrowLeft, ArrowRight, Check, ChevronLeft, ChevronRight, Ruler, ShoppingBag } from "lucide-react";
import { Link, useLocation, useRoute } from "wouter";
import { formatSAR, PRODUCTS, SIZES } from "@/lib/catalog";

export default function ProductDetail() {
  const [, params] = useRoute("/product/:id");
  const [, setLocation] = useLocation();
  const product = PRODUCTS.find((item) => item.id === Number(params?.id));
  const [imageIndex, setImageIndex] = useState(0);
  const [size, setSize] = useState("M");
  const [added, setAdded] = useState(false);
  if (!product) return <div className="simple-page"><Link href="/">Back to Kimo</Link><h1>Product not found.</h1></div>;
  const add = () => { setAdded(true); window.setTimeout(() => setAdded(false), 2200); };
  return <div className="detail-page"><header className="detail-header page-width"><Link href="/" className="detail-back"><ArrowLeft size={16} /> Kimo Studio</Link><Link href="/size-guide" className="detail-size-link"><Ruler size={15} /> Size guide</Link></header><main className="detail-main page-width"><div className="detail-gallery"><div className="detail-counter">0{imageIndex + 1} / 0{product.gallery.length}</div><img src={product.gallery[imageIndex]} alt={product.name} /><button className="gallery-arrow left" onClick={() => setImageIndex((imageIndex - 1 + product.gallery.length) % product.gallery.length)}><ChevronLeft /></button><button className="gallery-arrow right" onClick={() => setImageIndex((imageIndex + 1) % product.gallery.length)}><ChevronRight /></button><div className="gallery-thumbs">{product.gallery.map((image, index) => <button className={index === imageIndex ? "active" : ""} onClick={() => setImageIndex(index)} key={image}><img src={image} alt="" /></button>)}</div></div><div className="detail-copy"><p className="kicker">{product.category} / KIMO STUDIO</p><h1>{product.name}</h1><div className="detail-price">{"oldPrice" in product && <s>{formatSAR(product.oldPrice)}</s>} {formatSAR(product.price)}</div><p className="detail-description">{product.description}</p><div className="detail-rule" /><div className="detail-specs"><div><span>FIT</span><strong>{product.fit}</strong></div><div><span>FABRIC</span><strong>{product.material}</strong></div></div><p className="detail-long">{product.details}</p><div className="detail-size-heading"><span>Choose size</span><Link href="/size-guide"><Ruler size={14} /> View size guide</Link></div><div className="detail-sizes">{SIZES.map((item) => <button className={item === size ? "active" : ""} onClick={() => setSize(item)} key={item}>{item}</button>)}</div><button className="gold-button detail-add" onClick={add}>{added ? <><Check size={16} /> Added to bag</> : <><ShoppingBag size={16} /> Add to bag · {size}</>}<ArrowRight size={16} /></button><p className="detail-note">Free shipping over 100 SAR · Easy returns within 14 days</p></div></main><section className="detail-related page-width"><p className="kicker">YOU MAY ALSO LIKE</p><div className="related-grid">{PRODUCTS.filter((item) => item.id !== product.id).slice(0, 3).map((item) => <Link href={`/product/${item.id}`} key={item.id}><img src={item.image} alt={item.name} /><span>{item.name}</span><small>{formatSAR(item.price)}</small></Link>)}</div></section><footer className="detail-footer page-width"><span>© 2026 Kimo Studio.</span><Link href="/">Back to home <ArrowRight size={14} /></Link></footer></div>;
}
